from fastapi import APIRouter, HTTPException, UploadFile, File
from typing import List
from pydantic import BaseModel
from typing import Dict, Any
from ..services.rag_pipeline import RAGPipeline  

router = APIRouter()
rag_pipeline = RAGPipeline()

class Query(BaseModel):
    query: str
    top_k: int = 5

@router.post("/upload")
async def upload_papers(file: UploadFile = File(...)):
    try:
        content = await file.read()
        result = await rag_pipeline.process_and_store_document(content, file.filename)
        
        return {
            "status": "success",
            "filename": file.filename,
            "metadata": result["metadata"],
            "sections": {
                section: {
                    "chunk_count": len(section_data["chunks"]),
                    "start_page": section_data["start_page"],
                    "preview": section_data["chunks"][0][:200] if section_data["chunks"] else ""
                }
                for section, section_data in result["sections"].items()
            },
            "total_chunks": result["stored_chunks"],
            "content_type": file.content_type,
            "file_size": len(content)
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

@router.post("/query")
async def query_papers(query: str, top_k: int = 5) -> Dict[str, Any]:
    """
    Query the RAG system with a question.
    Returns answer generated by LLM along with source citations.
    """
    try:
        result = await rag_pipeline.query(query, top_k)
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))